#!/bin/bash

## standard build environment
## https://argoproj.github.io/argo-cd/user-guide/build-environment/
# ARGOCD_APP_NAME - name of application
# ARGOCD_APP_NAMESPACE - destination application namespace.
# ARGOCD_APP_REVISION - the resolved revision, e.g. f913b6cbf58aa5ae5ca1f8a2b149477aebcbd9d8
# ARGOCD_APP_SOURCE_PATH - the path of the app within the repo
# ARGOCD_APP_SOURCE_REPO_URL the repo's URL
# ARGOCD_APP_SOURCE_TARGET_REVISION - the target revision from the spec, e.g. master.
# KUBE_VERSION="<major>.<minor>"
# KUBE_API_VERSIONS="v1,apps/v1,..."

set -e

[[ "${ARGOCD_CMP_HELMFILE_DEBUG}" == "true" ]] && set -x

tmpfile=""
cleanup() {
  [[ -n "${tmpfile}" && -f "${tmpfile}" ]] && rm -r "${tmpfile}"
}
trap "cleanup" EXIT

echoerr() { printf "%s\n" "$*" >&2; }

[[ -z "${1}" ]] && echoerr "invalid invocation" && exit 1
phase=$1

helm=$(command -v helm)
helmfile=$(command -v helmfile)
helmfile="${helmfile} --helm-binary ${helm} --no-color --allow-no-matching-release"

[[ "${ARGOCD_APP_NAMESPACE}" ]] && helmfile+=" --namespace ${ARGOCD_APP_NAMESPACE}"
[[ "${HELMFILE_GLOBAL_OPTIONS}" ]] && helmfile+=" ${HELMFILE_GLOBAL_OPTIONS}"

helm_version=$(${helm} version --short --client)
helm_major_version=$(echo "${helm_version%+*}" | cut -d "." -f1 | sed 's/[^0-9]//g')
helm_minor_version=$(echo "${helm_version%+*}" | cut -d "." -f2 | sed 's/[^0-9]//g')

KUBE_VERSION=$(echo "${KUBE_VERSION}" | sed 's/[^0-9\.]*//g')

case $phase in
  "init")
    [[ ! -d "./charts" ]] && echoerr "no charts directory found, fetching..." && ${helmfile} fetch
    ;;
  "generate")
    INTERNAL_HELM_TEMPLATE_OPTIONS=""
    HELM_VALUES_FILE=""
    
    if [[ ${helm_major_version} -eq 3 && ${helm_minor_version} -ge 6 && -n "${KUBE_VERSION}" ]]; then
      INTERNAL_HELM_TEMPLATE_OPTIONS+=" --kube-version=${KUBE_VERSION}"
    fi

    if [[ ${helm_major_version} -eq 3 && -n "${KUBE_API_VERSIONS}" ]]; then
      IFS=',' read -ra api_versions <<< "${KUBE_API_VERSIONS}"
      for v in "${api_versions[@]}"; do
        INTERNAL_HELM_TEMPLATE_OPTIONS+=" --api-versions=$v"
      done
    fi

    if [[ "${ARGOCD_ENV_ADDITIONAL_VALUES}" ]]; then
      tmpfile=$(mktemp /tmp/helmfile-additional-values-XXXXXX)
      echo "${ARGOCD_ENV_ADDITIONAL_VALUES}" > "${tmpfile}"
      HELM_VALUES_FILE="--values ${tmpfile}"
    fi

    ${helmfile} template --skip-deps --args "${INTERNAL_HELM_TEMPLATE_OPTIONS}" ${HELM_VALUES_FILE}
    ;;
  *)
    echoerr "invalid invocation"
    exit 1
    ;;
esac
